{{- if .Values.s3.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.s3.secretName }}
type: Opaque
data:
  accessKey: {{ .Values.s3.accessKey | b64enc }}
  secretKey: {{ .Values.s3.secretKey | b64enc }}
{{- end }}
